apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deploy.name" . }}
    helm.sh/chart: {{ include "deploy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8009
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
